# this will deploy the safe / secure / tested app to Prod server
name: Deploy To Server

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH to Prod server - install dependencies & create folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Installing required packages"
            sudo apt-get update && sudo apt-get install -y docker.io docker-compose-v2
            sudo chmod 666 /var/run/docker.sock    # effective immediately, no new session needed
            mkdir -p ~/devops

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: ~/devops

      - name: SSH to Prod server - login & run the app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Running App"
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ vars.DOCKERHUB_USER }} --password-stdin
            export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
            export DOCKER_TAG=${{ github.sha }}
            cd ~/devops && docker compose down && docker compose up -d --pull always --force-recreate