name: Deploy flask app

on:
    workflow_dispatch:

jobs:

    deploy:

        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

        runs-on: self-hosted
        
        steps:
            - name: name checkout code
              uses: actions/checkout@v4

            - name : setup docker compose
              uses: docker/setup-buildx-action@v2

            - name: deploy with docker compose
              run: docker compose up -d --build

