# THis is Wokflow name
name: Hello Workflow 

# Runs on a Trigger 
on: 
  workflow_dispatch: 

# This are jobs inside workflow
jobs:

# This is the name of the job
  greet: 
  # This is GitHub Runner, each job runs on runner 
    runs-on: ubuntu-latest
    steps: 
      - name: Say Hello to users 
        run: echo "Hello Dosto"

      - name: Say Hello to Username
        run : echo "Hello $USER"
  Details:
    runs-on: ubuntu-latest
    steps:
      - name : Show what is the version of python, docker, etc.
        run: docker --version  && python --version 
      
