name: portfolio

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
    pages: write
    id-token: write
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest 
        
        environment:
            name: github-pages
            url: ${{ steps.deploy-pages.outputs.page_url }}  

        steps:
            #will get the access to portfolio code via pre-build actions
            - name: checkout code
              uses: actions/checkout@v4 

            # Setup GitHub pages 
            - name: setup github pages
              uses: actions/configure-pages@v4

            # static code artifats 
            - name: upload static file 
              uses: actions/upload-pages-artifact@v4
              with:
                path: "."

            - name: deploy to github pages
              uses: actions/deploy-pages@v4

